name: Auto merge

on:
  pull_request:
    branches:
    - master

jobs:
  auto-merge:
    runs-on: ubuntu-18.04
    steps:
    - uses: ridedott/merge-me-action@master
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_METHOD: MERGE
