name: Auto merge

on:
  pull_request:
    branches:
    - master

jobs:
  auto-merge:
    runs-on: ubuntu-18.04
    needs:
      - auto-approve
      - ci
    steps:
    - uses: ridedott/merge-me-action@master
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        GITHUB_TOKEN: "${{ secrets.TOKEN }}"
        MERGE_METHOD: MERGE
